config/routes.rb
Rails.application.routes.draw do
  resources :marker_types
  resources :game_analysis_markers
  resources :game_analyses
  resources :game_videos
  resources :games
  resources :teams
  resources :courses
  resources :user_roles
  resources :post_contents
  resources :posts
  resources :pages, only: [:show]

  namespace :users do
    resources :custom, except: [:create, :update]
    # post "custom/create", to: "custom#create", as: "create_custom"
    # patch "custom/update/:id", to: "custom#update", as: "update_custom"
    # post "custom/putrole/:id", to: "custom#put_role", as: "put_role_custom"
  end

  get 'users', to: 'users/custom#index', as: 'users'
  get 'about', to: 'pages#about', as: 'about'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'blog', to: redirect('http://esportfield.com/'), as: 'blog'
  post "subscribe", to: "pages#subscribe", as: "subscribe"
  post "send_message", to: "pages#send_message", as: "send_message"

  devise_for :users, controllers: {
    sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'users/confirmations'
  }

  # API
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      devise_for :users, controllers: { sessions: 'api/v1/users/sessions' }
      namespace :users do
        resource :sessions, only: [:create, :destroy, :show]
        resources :custom, only: [:index, :putrole, :create, :update, :destroy, :show]
        get 'founders', to: 'custom#index_founders', as: 'users_founders'
        get 'coaches', to: 'custom#index_coaches', as: 'users_coaches'
        get 'players', to: 'custom#index_players', as: 'users_players'
      end
      get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
      resources :courses, only: [:index, :create, :update, :destroy, :show]
      resources :teams, only: [:index, :create, :update, :destroy, :show]
      resources :user_roles, only: [:index, :create, :update, :destroy, :show]
      resources :marker_types, only: [:index, :create, :update, :destroy, :show]
      resources :games, only: [:index, :create, :update, :destroy, :show]
      resources :game_videos, only: [:index, :create, :update, :destroy, :show]
      resources :game_analyses, only: [:index, :create, :update, :destroy, :show]
      get 'game_analyses/index_by_coach/:coach_id', to: 'game_analyses#index_by_coach', as: 'index_by_coach'
      resources :game_analysis_markers, only: [:index, :create, :update, :destroy, :show]
      get 'game_analysis_markers/index_by_game_analysis/:game_analysis_id', to: 'game_analysis_markers#index_by_game_analysis', as: 'index_by_game_analysis'
    end
  end

  root to: 'pages#about'
end

app/controllers/api/v1/marker_types_controller.rb
class Api::V1::MarkerTypesController < ApplicationController
  before_action :set_marker_type, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :json

  # GET /marker_types
  # GET /marker_types.json
  def index
    @marker_types = MarkerType.all
    respond_with @marker_types
  end

  # GET /marker_types/1
  # GET /marker_types/1.json
  def show
    respond_with @marker_type
  end

  # POST /marker_types
  # POST /marker_types.json
  def create
    @marker_type = MarkerType.create(marker_type_params)
    respond_with @marker_type
  end

  # PATCH/PUT /marker_types/1
  # PATCH/PUT /marker_types/1.json
  def update
    respond_with @marker_type.update(marker_type_params)
  end

  # DELETE /marker_types/1
  # DELETE /marker_types/1.json
  def destroy
    respond_with @marker_type.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marker_type
      @marker_type = MarkerType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marker_type_params
      params.require(:marker_type).permit(:name, :color)
    end
end

app/controllers/marker_types_controller.rb
class MarkerTypesController < ApplicationController
  before_action :set_marker_type, only: [:show, :edit, :update, :destroy]

  # GET /marker_types
  # GET /marker_types.json
  def index
    @marker_types = MarkerType.all
  end

  # GET /marker_types/1
  # GET /marker_types/1.json
  def show
  end

  # GET /marker_types/new
  def new
    @marker_type = MarkerType.new
  end

  # GET /marker_types/1/edit
  def edit
  end

  # POST /marker_types
  # POST /marker_types.json
  def create
    @marker_type = MarkerType.new(marker_type_params)

    respond_to do |format|
      if @marker_type.save
        format.html { redirect_to @marker_type, notice: 'Marker type was successfully created.' }
        format.json { render :show, status: :created, location: @marker_type }
      else
        format.html { render :new }
        format.json { render json: @marker_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marker_types/1
  # PATCH/PUT /marker_types/1.json
  def update
    respond_to do |format|
      if @marker_type.update(marker_type_params)
        format.html { redirect_to @marker_type, notice: 'Marker type was successfully updated.' }
        format.json { render :show, status: :ok, location: @marker_type }
      else
        format.html { render :edit }
        format.json { render json: @marker_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marker_types/1
  # DELETE /marker_types/1.json
  def destroy
    @marker_type.destroy
    respond_to do |format|
      format.html { redirect_to marker_types_url, notice: 'Marker type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marker_type
      @marker_type = MarkerType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marker_type_params
      params.require(:marker_type).permit(:name, :color)
    end
end

app/helpers/marker_types_helper.rb
module MarkerTypesHelper
end

app/views/marker_types/_form.html.erb
<%= form_with(model: marker_type, local: true) do |form| %>
  <% if marker_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(marker_type.errors.count, "error") %> prohibited this marker_type from being saved:</h2>

      <ul>
      <% marker_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/marker_types/edit.html.erb
<h1>Editing Marker Type</h1>

<%= render 'form', marker_type: @marker_type %>

<%= link_to 'Show', @marker_type %> |
<%= link_to 'Back', marker_types_path %>

app/views/marker_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Marker Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @marker_types.each do |marker_type| %>
      <tr>
        <td><%= marker_type.name %></td>
        <td><%= marker_type.color %></td>
        <td><%= link_to 'Show', marker_type %></td>
        <td><%= link_to 'Edit', edit_marker_type_path(marker_type) %></td>
        <td><%= link_to 'Destroy', marker_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Marker Type', new_marker_type_path %>

app/views/marker_types/new.html.erb
<h1>New Marker Type</h1>

<%= render 'form', marker_type: @marker_type %>

<%= link_to 'Back', marker_types_path %>

app/views/marker_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @marker_type.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @marker_type.color %>
</p>

<%= link_to 'Edit', edit_marker_type_path(@marker_type) %> |
<%= link_to 'Back', marker_types_path %>