config/routes.rb
Rails.application.routes.draw do
  resources :marker_types
  resources :game_analysis_markers
  resources :game_analyses
  resources :game_videos
  resources :games
  resources :teams
  resources :courses
  resources :user_roles
  resources :post_contents
  resources :posts
  resources :pages, only: [:show]

  namespace :users do
    resources :custom, except: [:create, :update]
    # post "custom/create", to: "custom#create", as: "create_custom"
    # patch "custom/update/:id", to: "custom#update", as: "update_custom"
    # post "custom/putrole/:id", to: "custom#put_role", as: "put_role_custom"
  end

  get 'users', to: 'users/custom#index', as: 'users'
  get 'about', to: 'pages#about', as: 'about'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'blog', to: redirect('http://esportfield.com/'), as: 'blog'
  post "subscribe", to: "pages#subscribe", as: "subscribe"
  post "send_message", to: "pages#send_message", as: "send_message"

  devise_for :users, controllers: {
    sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'users/confirmations'
  }

  # API
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      devise_for :users, controllers: { sessions: 'api/v1/users/sessions' }
      namespace :users do
        resource :sessions, only: [:create, :destroy, :show]
        resources :custom, only: [:index, :putrole, :create, :update, :destroy, :show]
        get 'founders', to: 'custom#index_founders', as: 'users_founders'
        get 'coaches', to: 'custom#index_coaches', as: 'users_coaches'
        get 'players', to: 'custom#index_players', as: 'users_players'
      end
      get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
      resources :courses, only: [:index, :create, :update, :destroy, :show]
      resources :teams, only: [:index, :create, :update, :destroy, :show]
      resources :user_roles, only: [:index, :create, :update, :destroy, :show]
      resources :marker_types, only: [:index, :create, :update, :destroy, :show]
      resources :games, only: [:index, :create, :update, :destroy, :show]
      resources :game_videos, only: [:index, :create, :update, :destroy, :show]
      resources :game_analyses, only: [:index, :create, :update, :destroy, :show]
      get 'game_analyses/index_by_coach/:coach_id', to: 'game_analyses#index_by_coach', as: 'index_by_coach'
      resources :game_analysis_markers, only: [:index, :create, :update, :destroy, :show]
      get 'game_analysis_markers/index_by_game_analysis/:game_analysis_id', to: 'game_analysis_markers#index_by_game_analysis', as: 'index_by_game_analysis'
    end
  end

  root to: 'pages#about'
end

app/controllers/api/v1/game_analyses_controller.rb
class Api::V1::GameAnalysesController < ApplicationController
  before_action :set_game_analysis, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :json

  # GET /game_analyses
  # GET /game_analyses.json
  def index
    @game_analyses = GameAnalysis.all
    respond_with @game_analyses
  end

  def index_by_coach
    @game_analyses = GameAnalysis.where(coach_id: params[:coach_id])
    respond_with @game_analyses
  end

  # GET /game_analyses/1
  # GET /game_analyses/1.json
  def show
    respond_with @game_analysis
  end

  # POST /game_analyses
  # POST /game_analyses.json
  def create
    @game_analysis = GameAnalysis.create(game_analysis_params)
    respond_with @game_analysis
  end

  # PATCH/PUT /game_analyses/1
  # PATCH/PUT /game_analyses/1.json
  def update
    respond_with @game_analysis.update(game_analysis_params)
  end

  # DELETE /game_analyses/1
  # DELETE /game_analyses/1.json
  def destroy
    respond_with @game_analysis.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_analysis
      @game_analysis = GameAnalysis.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_analysis_params
      params.require(:game_analysis).permit(:game_video_id, :summary, :recommendation, :coach_id)
    end
end

app/controllers/game_analyses_controller.rb
class GameAnalysesController < ApplicationController
  before_action :set_game_analysis, only: [:show, :edit, :update, :destroy]

  # GET /game_analyses
  # GET /game_analyses.json
  def index
    @game_analyses = GameAnalysis.all
  end

  # GET /game_analyses/1
  # GET /game_analyses/1.json
  def show
  end

  # GET /game_analyses/new
  def new
    @game_analysis = GameAnalysis.new
  end

  # GET /game_analyses/1/edit
  def edit
  end

  # POST /game_analyses
  # POST /game_analyses.json
  def create
    @game_analysis = GameAnalysis.new(game_analysis_params)

    respond_to do |format|
      if @game_analysis.save
        format.html { redirect_to @game_analysis, notice: 'Game analysis was successfully created.' }
        format.json { render :show, status: :created, location: @game_analysis }
      else
        format.html { render :new }
        format.json { render json: @game_analysis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_analyses/1
  # PATCH/PUT /game_analyses/1.json
  def update
    respond_to do |format|
      if @game_analysis.update(game_analysis_params)
        format.html { redirect_to @game_analysis, notice: 'Game analysis was successfully updated.' }
        format.json { render :show, status: :ok, location: @game_analysis }
      else
        format.html { render :edit }
        format.json { render json: @game_analysis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_analyses/1
  # DELETE /game_analyses/1.json
  def destroy
    @game_analysis.destroy
    respond_to do |format|
      format.html { redirect_to game_analyses_url, notice: 'Game analysis was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_analysis
      @game_analysis = GameAnalysis.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_analysis_params
      params.require(:game_analysis).permit(:game_video_id, :summary, :recommendation, :coach_id)
    end
end

app/helpers/game_analyses_helper.rb
module GameAnalysesHelper
end

app/views/game_analyses/_form.html.erb
<%= form_with(model: game_analysis, local: true) do |form| %>
  <% if game_analysis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game_analysis.errors.count, "error") %> prohibited this game_analysis from being saved:</h2>

      <ul>
      <% game_analysis.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :game_video %>
    <%= form.text_field :game_video %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_field :summary %>
  </div>

  <div class="field">
    <%= form.label :recommendation %>
    <%= form.text_field :recommendation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/game_analyses/edit.html.erb
<h1>Editing Game Analysis</h1>

<%= render 'form', game_analysis: @game_analysis %>

<%= link_to 'Show', @game_analysis %> |
<%= link_to 'Back', game_analyses_path %>

app/views/game_analyses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Game Analyses</h1>

<table>
  <thead>
    <tr>
      <th>Game video</th>
      <th>Link</th>
      <th>Summary</th>
      <th>Recommendation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @game_analyses.each do |game_analysis| %>
      <tr>
        <td><%= game_analysis.game_video %></td>
        <td><%= game_analysis.link %></td>
        <td><%= game_analysis.summary %></td>
        <td><%= game_analysis.recommendation %></td>
        <td><%= link_to 'Show', game_analysis %></td>
        <td><%= link_to 'Edit', edit_game_analysis_path(game_analysis) %></td>
        <td><%= link_to 'Destroy', game_analysis, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game Analysis', new_game_analysis_path %>

app/views/game_analyses/new.html.erb
<h1>New Game Analysis</h1>

<%= render 'form', game_analysis: @game_analysis %>

<%= link_to 'Back', game_analyses_path %>

app/views/game_analyses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game video:</strong>
  <%= @game_analysis.game_video %>
</p>

<p>
  <strong>Link:</strong>
  <%= @game_analysis.link %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @game_analysis.summary %>
</p>

<p>
  <strong>Recommendation:</strong>
  <%= @game_analysis.recommendation %>
</p>

<%= link_to 'Edit', edit_game_analysis_path(@game_analysis) %> |
<%= link_to 'Back', game_analyses_path %>