config/routes.rb
Rails.application.routes.draw do
  resources :marker_types
  resources :game_analysis_markers
  resources :game_analyses
  resources :game_videos
  resources :games
  resources :teams
  resources :courses
  resources :user_roles
  resources :post_contents
  resources :posts
  resources :pages, only: [:show]

  namespace :users do
    resources :custom, except: [:create, :update]
    # post "custom/create", to: "custom#create", as: "create_custom"
    # patch "custom/update/:id", to: "custom#update", as: "update_custom"
    # post "custom/putrole/:id", to: "custom#put_role", as: "put_role_custom"
  end

  get 'users', to: 'users/custom#index', as: 'users'
  get 'about', to: 'pages#about', as: 'about'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'blog', to: redirect('http://esportfield.com/'), as: 'blog'
  post "subscribe", to: "pages#subscribe", as: "subscribe"
  post "send_message", to: "pages#send_message", as: "send_message"

  devise_for :users, controllers: {
    sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'users/confirmations'
  }

  # API
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      devise_for :users, controllers: { sessions: 'api/v1/users/sessions' }
      namespace :users do
        resource :sessions, only: [:create, :destroy, :show]
        resources :custom, only: [:index, :putrole, :create, :update, :destroy, :show]
        get 'founders', to: 'custom#index_founders', as: 'users_founders'
        get 'coaches', to: 'custom#index_coaches', as: 'users_coaches'
        get 'players', to: 'custom#index_players', as: 'users_players'
      end
      get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
      resources :courses, only: [:index, :create, :update, :destroy, :show]
      resources :teams, only: [:index, :create, :update, :destroy, :show]
      resources :user_roles, only: [:index, :create, :update, :destroy, :show]
      resources :marker_types, only: [:index, :create, :update, :destroy, :show]
      resources :games, only: [:index, :create, :update, :destroy, :show]
      resources :game_videos, only: [:index, :create, :update, :destroy, :show]
      resources :game_analyses, only: [:index, :create, :update, :destroy, :show]
      get 'game_analyses/index_by_coach/:coach_id', to: 'game_analyses#index_by_coach', as: 'index_by_coach'
      resources :game_analysis_markers, only: [:index, :create, :update, :destroy, :show]
      get 'game_analysis_markers/index_by_game_analysis/:game_analysis_id', to: 'game_analysis_markers#index_by_game_analysis', as: 'index_by_game_analysis'
    end
  end

  root to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attributes :name,  :validate => true
  attributes :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attributes :message
  attributes :nickname,   :captcha => true

  def headers
    {
      :to => "esportfield1@gmail.com",
      :subject => "Contact Form",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :coach, class_name: "User"
  belongs_to :game

  def to_s
    self.game
  end
end

app/models/game.rb
class Game < ApplicationRecord
  mount_uploader :logo, ImageUploader

  has_many :users
  has_many :teams
  has_many :courses
  has_many :game_videos

  def to_s
    self.name
  end
end

app/models/game_analysis.rb
class GameAnalysis < ApplicationRecord
  belongs_to :game_video
  belongs_to :coach, class_name: "User"
  has_many :game_analysis_markers

  def to_s
    self.game_video.game
  end
end

app/models/game_video.rb
class GameVideo < ApplicationRecord
  mount_uploader :video, VideoUploader

  has_many :game_analyses
  belongs_to :game
  belongs_to :player, class_name: "User"

  def to_s
    self.game.name
  end
end

app/models/marker_type.rb
class MarkerType < ApplicationRecord
  has_many :game_analysis_markers

  def to_s
    self.name
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :post_contents, inverse_of: :post
  accepts_nested_attributes_for :post_contents, reject_if: :all_blank, allow_destroy: true

  mount_uploader :image, ImageUploader
end

app/models/post_content.rb
class PostContent < ApplicationRecord
  belongs_to :post
  mount_uploader :image_content, ImageUploader

  validates :image_content, presence: true
end

app/models/team.rb
class Team < ApplicationRecord
  mount_uploader :logo, ImageUploader

  belongs_to :founder, class_name: "User"
  belongs_to :game

  def to_s
    self.name
  end
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_token_authenticatable
  mount_uploader :avatar, ImageUploader

  has_many :teams
  has_many :courses
  belongs_to :user_role
  belongs_to :game

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def is_app_admin?
    user_role.level == 0 ? true : false
  end

  def is_founder?
    user_role.level == 1 ? true : false
  end

  def is_coach?
    user_role.level == 2 ? true : false
  end

  def is_player?
    user_role.level == 3 ? true : false
  end

  def to_s
    self.nickname
  end
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  has_many :users

  def to_s
    self.name
  end
end

app/controllers/post_contents_controller.rb
class PostContentsController < ApplicationController
  before_action :set_post_content, only: [:show, :edit, :update, :destroy]

  # GET /post_contents
  # GET /post_contents.json
  def index
    @post_contents = PostContent.all
  end

  # GET /post_contents/1
  # GET /post_contents/1.json
  def show
  end

  # GET /post_contents/new
  def new
    @post_content = PostContent.new
  end

  # GET /post_contents/1/edit
  def edit
  end

  # POST /post_contents
  # POST /post_contents.json
  def create
    @post_content = PostContent.new(post_content_params)

    respond_to do |format|
      if @post_content.save
        format.html { redirect_to @post_content, notice: 'Post content was successfully created.' }
        format.json { render :show, status: :created, location: @post_content }
      else
        format.html { render :new }
        format.json { render json: @post_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_contents/1
  # PATCH/PUT /post_contents/1.json
  def update
    respond_to do |format|
      if @post_content.update(post_content_params)
        format.html { redirect_to @post_content, notice: 'Post content was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_content }
      else
        format.html { render :edit }
        format.json { render json: @post_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_contents/1
  # DELETE /post_contents/1.json
  def destroy
    @post_content.destroy
    respond_to do |format|
      format.html { redirect_to post_contents_url, notice: 'Post content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_content
      @post_content = PostContent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_content_params
      params.require(:post_content).permit(:text_content, :subtitle_content, :image_content, :post_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/game_videos_helper.rb
module GameVideosHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/marker_types_helper.rb
module MarkerTypesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_contents_helper.rb
module PostContentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/user_roles_helper.rb
module UserRolesHelper
end

app/views/post_contents/_form.html.erb
<%= form_with(model: post_content, local: true) do |form| %>
  <% if post_content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post_content.errors.count, "error") %> prohibited this post_content from being saved:</h2>

      <ul>
      <% post_content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text_content %>
    <%= form.text_field :text_content %>
  </div>

  <div class="field">
    <%= form.label :subtitle_content %>
    <%= form.text_field :subtitle_content %>
  </div>

  <div class="field">
    <%= form.label :image_content %>
    <%= form.text_field :image_content %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.text_field :post_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/post_contents/edit.html.erb
<h1>Editing Post Content</h1>

<%= render 'form', post_content: @post_content %>

<%= link_to 'Show', @post_content %> |
<%= link_to 'Back', post_contents_path %>

app/views/post_contents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Post Contents</h1>

<table>
  <thead>
    <tr>
      <th>Text content</th>
      <th>Subtitle content</th>
      <th>Image content</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_contents.each do |post_content| %>
      <tr>
        <td><%= post_content.text_content %></td>
        <td><%= post_content.subtitle_content %></td>
        <td><%= post_content.image_content %></td>
        <td><%= post_content.post %></td>
        <td><%= link_to 'Show', post_content %></td>
        <td><%= link_to 'Edit', edit_post_content_path(post_content) %></td>
        <td><%= link_to 'Destroy', post_content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post Content', new_post_content_path %>

app/views/post_contents/new.html.erb
<h1>New Post Content</h1>

<%= render 'form', post_content: @post_content %>

<%= link_to 'Back', post_contents_path %>

app/views/post_contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text content:</strong>
  <%= @post_content.text_content %>
</p>

<p>
  <strong>Subtitle content:</strong>
  <%= @post_content.subtitle_content %>
</p>

<p>
  <strong>Image content:</strong>
  <%= @post_content.image_content %>
</p>

<p>
  <strong>Post:</strong>
  <%= @post_content.post %>
</p>

<%= link_to 'Edit', edit_post_content_path(@post_content) %> |
<%= link_to 'Back', post_contents_path %>