config/routes.rb
Rails.application.routes.draw do
  resources :marker_types
  resources :game_analysis_markers
  resources :game_analyses
  resources :game_videos
  resources :games
  resources :teams
  resources :courses
  resources :user_roles
  resources :post_contents
  resources :posts
  resources :pages, only: [:show]

  namespace :users do
    resources :custom, except: [:create, :update]
    # post "custom/create", to: "custom#create", as: "create_custom"
    # patch "custom/update/:id", to: "custom#update", as: "update_custom"
    # post "custom/putrole/:id", to: "custom#put_role", as: "put_role_custom"
  end

  get 'users', to: 'users/custom#index', as: 'users'
  get 'about', to: 'pages#about', as: 'about'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'blog', to: redirect('http://esportfield.com/'), as: 'blog'
  post "subscribe", to: "pages#subscribe", as: "subscribe"
  post "send_message", to: "pages#send_message", as: "send_message"

  devise_for :users, controllers: {
    sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'users/confirmations'
  }

  # API
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      devise_for :users, controllers: { sessions: 'api/v1/users/sessions' }
      namespace :users do
        resource :sessions, only: [:create, :destroy, :show]
        resources :custom, only: [:index, :putrole, :create, :update, :destroy, :show]
        get 'founders', to: 'custom#index_founders', as: 'users_founders'
        get 'coaches', to: 'custom#index_coaches', as: 'users_coaches'
        get 'players', to: 'custom#index_players', as: 'users_players'
      end
      get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
      resources :courses, only: [:index, :create, :update, :destroy, :show]
      resources :teams, only: [:index, :create, :update, :destroy, :show]
      resources :user_roles, only: [:index, :create, :update, :destroy, :show]
      resources :marker_types, only: [:index, :create, :update, :destroy, :show]
      resources :games, only: [:index, :create, :update, :destroy, :show]
      resources :game_videos, only: [:index, :create, :update, :destroy, :show]
      resources :game_analyses, only: [:index, :create, :update, :destroy, :show]
      get 'game_analyses/index_by_coach/:coach_id', to: 'game_analyses#index_by_coach', as: 'index_by_coach'
      resources :game_analysis_markers, only: [:index, :create, :update, :destroy, :show]
      get 'game_analysis_markers/index_by_game_analysis/:game_analysis_id', to: 'game_analysis_markers#index_by_game_analysis', as: 'index_by_game_analysis'
    end
  end

  root to: 'pages#about'
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_token_authenticatable
  mount_uploader :avatar, ImageUploader

  has_many :teams
  has_many :courses
  belongs_to :user_role
  belongs_to :game

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def is_app_admin?
    user_role.level == 0 ? true : false
  end

  def is_founder?
    user_role.level == 1 ? true : false
  end

  def is_coach?
    user_role.level == 2 ? true : false
  end

  def is_player?
    user_role.level == 3 ? true : false
  end

  def to_s
    self.nickname
  end
end

app/controllers/api/v1/users/custom_controller.rb
class Api::V1::Users::CustomController < ApplicationController
	before_action :set_user, only: [:show, :update, :destroy, :put_role]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
	respond_to :json

	def index
		@users = User.all
		respond_with @users
	end

	def index_founders
		@users = User.includes(:user_role).where(user_roles: {level: 1})
		respond_with @users
	end

	def index_coaches
		@users = User.includes(:user_role).where(user_roles: {level: 2})
		respond_with @users
	end

	def index_players
		@users = User.includes(:user_role).where(user_roles: {level: 3})
		respond_with @users
	end

	def show
	  respond_with @user
	end

	def put_role
		# @user_role = UserRole.where(id: params[:user_role_id]).first
		# respond_to do |format|
		# 	if @user.update({user_role_id: @user_role.id})
		# 		format.html { redirect_to users_custom_index_path, notice: 'Rola użytkownika została edytowana pomyślnie.' }
		# 	end
		# end
	end

	def create
		@user = User.create(user_params)
		respond_with @user
	end

	# PATCH/PUT /users/1
	# PATCH/PUT /users/1.json
	def update
		if current_user.is_admin? || current_user.id == @user.id
			respond_with @user.update(user_params)
		end
	end

	# DELETE /users/1
	# DELETE /users/1.json
	def destroy
		respond_with @user.destroy
	end

	private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
			@user = User.find(params[:id])
    end

		# Never trust parameters from the scary internet, only allow the white list through.
		def user_params
			params.require(:user).permit(:email, :password, :nickname, :user_role_id, :game_id, :avatar)
		end

end

app/controllers/api/v1/users/sessions_controller.rb
class Api::V1::Users::SessionsController < ApplicationController
  def show
    current_user ? head(:ok) : head(:unauthorized)
  end

  def create
    user = User.where(email: params[:email]).first
    if user&.valid_password?(params[:password])
      render json: user.as_json, status: :created
    else
      head(:unauthorized)
    end
  end

  def destroy
    current_user&.authentication_token = nil
    if current_user.save
      head(:ok)
    else
      head(:unauthorized)
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/custom_controller.rb
class Users::CustomController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]
	# before_action :authenticate_user!

	def index
	  @users = User.all
		# @user_roles = UserRole.all
	end

	def show
	end

	def new
		@user = User.new
	end

	def edit
	end

	# def put_role
	# 	@user_role = UserRole.where(id: params[:user_role_id]).first
  #
	# 	respond_to do |format|
	# 		if @user.update({user_role_id: @user_role.id})
	# 			format.html { redirect_to users_custom_index_path, notice: 'Rola użytkownika została edytowana pomyślnie.' }
	# 		end
	# 	end
	# end

	def create
		@user = User.new(user_params)

		respond_to do |format|
			if @user.save
				format.html { redirect_to users_custom_path(@user), notice: 'User was successfully created.' }
				format.json { render :show, status: :created, location: users_custom_path(@user) }
			else
				format.html { render :new }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /users/1
	# PATCH/PUT /users/1.json
	def update
		respond_to do |format|
			if @user.update(user_params)
				format.html { redirect_to users_custom_path(@user), notice: 'User was successfully updated.' }
				format.json { render :show, status: :ok, location: users_custom_path(@user) }
			else
				format.html { render :edit }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /users/1
	# DELETE /users/1.json
	def destroy
		@user.destroy
		respond_to do |format|
			format.html { redirect_to users_custom_index_path, notice: 'User was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

		# Never trust parameters from the scary internet, only allow the white list through.
		def user_params
			params.require(:user).permit(:nickname, :email, :password, :user_role_id, :game_id, :avatar)
		end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    UserMailer.signup_confirmation(@user).deliver
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :game_id, :user_role_id, :avatar])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :avatar])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/users/custom/_form.html.erb
<%= form_for([:users, user], url: (user.new_record? ? users_create_custom_path : users_update_custom_path(user)) ) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="form-group"> -->
    <%#= f.label "Utworzony przez" %>
    <%#= f.select :created_by_user_id, User.all.map{ |c| [c.email, c.id]}, {selected: created_by_user_id}, {class: 'form-control'} %>
    <%#= f.text_field :app_module_id %>
  <!-- </div> -->

  <div class="form-group">
    <%= f.label :organization_id %>
    <%= f.select :organization_id, Organization.all.map{ |c| [c.name, c.id]}, {selected: f.object.organization_id}, {class: 'form-control'} %>
  </div>

  <div class="form-group">
    <%= f.label :user_role_id %>
    <%= f.select :user_role_id, UserRole.all.map{ |c| [c.name, c.id]}, {selected: f.object.user_role_id}, {class: 'form-control'} %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <!-- <div class="form-group"> -->
    <%#= f.label "Imię" %>
    <%#= f.text_field :first_name, class: 'form-control' %>
  <!-- </div> -->

  <!-- <div class="form-group"> -->
    <%#= f.label "Nazwisko" %>
    <%#= f.text_field :last_name, class: 'form-control' %>
  <!-- </div> -->

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/custom/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user, action: 'update' %>

<%= link_to 'Show', users_custom_path(@user) %> |
<%= link_to 'Back', users_custom_index_path %>

app/views/users/custom/index.html.erb
<div class="min-height-100 pt-20-vh">
  <div class="container-fluid">
    <div class="content-center brand">
      <h1 class="h1-seo"><%= t('.users') %></h1>
      <!-- <div class="card card-plain">
        <div class="card-header">
        </div>
        <div class="card-body"> -->
    </div>
            <div class="table-responsive-sm">
              <table class="table table-hover table-active">
                <thead >
                  <tr>
                    <th>#</th>
                    <th>ID</th>
                    <th>Nickname</th>
                    <th>Email</th>
                    <!-- <th scope="col">User Role</th> -->
                    <!-- <th scope="col">Set Roles</th> -->
                    <!-- <th scope="col">Last Login</th>
                    <th scope="col">Sign In Count</th> -->
                    <th>Registration Date</th>
                    <th class="text-right" colspan="3">Options</th>
                  </tr>
                </thead>
                <tbody>
                  <% @users.each_with_index do |user, index| %>
                    <tr>
                      <td><%= index+1 %></td>
                      <td><%= user.id %></td>
                      <td><%= user.nickname %></td>
                      <td><%= user.email %></td>
                      <!-- <td><%#= user.user_role %></td> -->

                      <%# if user.user_role.level == 0 %>
                        <%# @status_a = "active" %>
                      <%# else %>
                        <%# @status_a = "" %>
                      <%# end %>

                      <%# if user.user_role.level == 1 %>
                        <%# @status_t = "active" %>
                      <%# else %>
                        <%# @status_t = "" %>
                      <%# end %>

                      <%# if user.user_role.level == 2 %>
                        <%# @status_u = "active" %>
                      <%# else %>
                        <%# @status_u = "" %>
                      <%# end %>

                      <!-- <td> -->
                        <%# if user != current_user %>
                          <!-- <div class="pull-left"> -->
                            <%#= button_to "App Admin", users_put_role_custom_path(id: user.id, user_role_id: UserRole.where(level: 0).first.id), method: :post, class: "btn btn-primary btn-sm "+@status_a %>
                          <!-- </div> -->
                          <!-- <div class="pull-left"> -->
                            <%#= button_to "Organization Leader", users_put_role_custom_path(id: user.id, user_role_id: UserRole.where(level: 1).first.id), method: :post, class: "btn btn-primary btn-sm "+@status_t %>
                          <!-- </div> -->
                          <!-- <div class="pull-left"> -->
                            <%#= button_to "Organization User", users_put_role_custom_path(id: user.id, user_role_id: UserRole.where(level: 2).first.id), method: :post, class: "btn btn-primary btn-sm "+@status_u %>
                          <!-- </div> -->
                        <%# else %>
                        <%# end %>
                      <!-- </td> -->
                      <!-- <td><%#= user.last_sign_in_at %></td> -->
                      <!-- <td><%#= user.sign_in_count %></td> -->
                      <td><%= user.created_at %></td>
                      <td class="td-actions text-right">
                        <%= link_to users_custom_path(user), { class: "btn btn-icon btn-primary btn-round", data: { toggle: "tooltip", original_title: "Show" }} do %><i class="tim-icons icon-paper"></i><% end %>
                      </td>
                      <td class="td-actions text-right">
                        <%= link_to edit_users_custom_path(user), { class: "btn btn-icon btn-info btn-round", data: { toggle: 'tooltip', original_title: "Edit" }} do %><i class="tim-icons icon-pencil"></i><% end %>
                      </td>
                      <td class="td-actions text-right">
                        <%= link_to users_custom_path(user), { class: "btn btn-icon btn-danger btn-round", method: :delete, data: { toggle: 'tooltip', original_title: "Delete", confirm: "Are you sure?" }} do %><i class="tim-icons icon-trash-simple"></i><% end %>
                      </td>

                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          <%#= link_to 'New User', new_users_custom_path, user: @user, action: 'create', class: "btn btn-success", role: "button" %>
        <!-- </div>
      </div> -->

  </div>
</div>

app/views/users/custom/new.html.erb
<div class="container">
  <h1>New User</h1>

  <%= render 'form', user: @user, action: 'create' %>

  <%= link_to 'Back', users_custom_index_path %>
</div>

app/views/users/custom/show.html.erb
<div class="container">
  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>

  <p>
    <strong>User Role:</strong>
    <%= @user.user_role %>
  </p>

  <p>
    <strong>Organization:</strong>
    <%= @user.organization %>
  </p>

  <%#= link_to 'Edytuj', edit_training_process_path(@user) %>
  <%= link_to 'Back', users_custom_index_path %>
</div>